[package]
name = "editor-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish = false
description = "Layered settings, keymap, themes and project detection"

[dependencies]
anyhow.workspace = true
directories.workspace = true
serde.workspace = true
toml_edit.workspace = true

[lints]
workspace = true
